version: "3"
services:
  aquarius:
    image: oceanprotocol/aquarius:${AQUARIUS_VERSION:-latest}
    ports:
      - 5000:5000
    networks:
      backend:
        ipv4_address: 172.15.0.5
    depends_on:
      - elasticsearch
    environment:
      DB_MODULE: ${DB_MODULE}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: ${DB_SSL}
      DB_VERIFY_CERTS: ${DB_VERIFY_CERTS}
      DB_CA_CERTS: ${DB_CA_CERTS}
      DB_CLIENT_KEY: ${DB_CLIENT_KEY}
      DB_CLIENT_CERT: ${DB_CLIENT_CERT}
      LOG_LEVEL: DEBUG
      PRIVATE_KEY: ${PK1}
      ARTIFACTS_PATH: "/ocean-contracts/artifacts"
      ADDRESS_FILE: "/ocean-contracts/artifacts/address.json"
      DEPLOY_CONTRACTS: "false"
      NETWORK_NAME: ${CONTRACTS_NETWORK_NAME}
      EVENTS_RPC: "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
      EVENTS_ALLOW: "0"
      RUN_EVENTS_MONITOR: "1"
    volumes:
      - ${OCEAN_ARTIFACTS_FOLDER}:/ocean-contracts/artifacts/
